### ISSUE TITLE
Harm-P and Harm-C Datasets

### ISSUE THREAD

**Issue by adrielkuek** [LCS2-IIITD/MOMENTA#1]
Hi, I'm trying to reproduce the results for the Momenta framework as seen from the paper. Understand that the HarMeme dataset is a large-scale dataset of close to almost 10k memes. However the links for the gdrive download to the 2 datasets only has 150 meme images each. Would it be possible to release to entire HarMeme dataset for testing?

Thanks and appreciate it!

**Comment by ghost** [comment]
Maybe after their paper got accepted, they will publish the full dataset.
But have you fixed the wrong indexes problem in JSON files? As I stated here: https://github.com/LCS2-IIITD/MOMENTA/issues/2

**Comment by ngthanhtin** [comment]
Maybe after their paper got accepted, they will publish the full dataset.
But have you fixed the wrong indexes problem in JSON files? As I stated here: https://github.com/LCS2-IIITD/MOMENTA/issues/2

**Comment by Shiv681991** [comment]
The links to the complete dataset have been provided now.

**Comment by Shiv681991** [comment]
The links to the complete dataset have been added now to the main readme.

**Comment by shiv6891** [comment]
The complete dataset links are now added to the main readme.
