### ISSUE TITLE
Wrong index in json file?

### ISSUE THREAD

**Issue by ghost** [LCS2-IIITD/MOMENTA#2]
Hi, thanks for providing the code and dataset to reproduce, but in the JSON files, there are a lot of image indexes that don't have the corresponding images in the image folders.

So, could you please provide an accurate dataset?

Best,
Tin

**Comment by Shiv681991** [comment]
The complete dataset links have been added now in the main readme.

**Comment by shiv6891** [comment]
The complete dataset link is now added to the main readme.
