### ISSUE TITLE
Duplicated records in Harm-P dataset 

### ISSUE THREAD

**Issue by mingshanhee** [LCS2-IIITD/MOMENTA#3]
Hi authors, thanks for releasing the dataset. I am keen in using the Harm-C and Harm-P dataset for my own research experiments. However, I found out that the Harm-P dataset contains many duplicates across the training, validation and test dataset splits. To be precise, there are 1489, 5 and 155 duplicates in the training, validation and testing dataset splits (Refer to the screenshots attached).

Hence, can you please check out the dataset via the GitHub's download link and kindly provide an accurate dataset? Thank you in advance!

![Harm-P's Train Set](https://github.com/LCS2-IIITD/MOMENTA/assets/4586211/e8262a0f-03d9-438c-a85d-d36fe6c25290)

![Harm-P's Val Set](https://github.com/LCS2-IIITD/MOMENTA/assets/4586211/e422156d-6f38-4412-9c90-3c50a0d010fc)

![Harm-P's Test Set](https://github.com/LCS2-IIITD/MOMENTA/assets/4586211/d7bd3570-c5e2-409f-bc7d-00050726bb6b)

**Comment by shiv6891** [comment]
Hi @mingshanhee, thanks for the heads up. The files are now updated. Please se the udpated readme and repo for further details.
